### ISSUE TITLE
1.0.0-beta.4  roadhog buildDll  error

### ISSUE THREAD

**Issue by kingyang** [sorrycc/roadhog#300]
#### Environment(required) | 环境（必填）

node:7.10.0/npm:4.2.0
node:8.0.0/npm:5.0.3
```json
{
  "private": true,
  "scripts": {
    "start": "roadhog server",
    "build": "roadhog build",
    "dll": "roadhog buildDll",
    "lint": "eslint --ext .js src test",
    "precommit": "npm run lint"
  },
  "engines": {
    "install-node": "6.9.2"
  },
  "dependencies": {
    "babel-runtime": "^6.9.2",
    "react": "^15.4.0",
    "react-dom": "^15.4.0"
  },
  "devDependencies": {
    "dva": "1.3.0-beta1",
    "babel-eslint": "^7.1.1",
    "babel-plugin-dva-hmr": "^0.3.2",
    "babel-plugin-transform-runtime": "^6.9.0",
    "eslint": "^3.12.2",
    "eslint-config-airbnb": "^13.0.0",
    "eslint-plugin-import": "^2.2.0",
    "eslint-plugin-jsx-a11y": "^2.2.3",
    "eslint-plugin-react": "^6.8.0",
    "expect": "^1.20.2",
    "husky": "^0.12.0",
    "redbox-react": "^1.3.2",
    "roadhog": "^1.0.0-beta.4",
    "webpack": "^2.6.1"
  }
}

```

#### What did you do? Please provide steps to re-produce your problem.（请提供复现步骤）
执行 npm run  dll 报错

#### What happen?（发生了何种非正常现象）
```bash
D:\code\demo\myapp\node_modules\roadhog\node_modules\webpack\lib\webpack.js:19
                throw new WebpackOptionsValidationError(webpackOptionsValidationErrors);
                ^

WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema
.
 - configuration.resolve has an unknown property 'modulesDirectories'. These properties are valid:
   object { alias?, aliasFields?, cachePredicate?, descriptionFiles?, enforceExtension?, enforceModuleExtension?, extensions?, fileSystem?, mainFields?,
mainFiles?, moduleExtensions?, modules?, plugins?, resolver?, symlinks?, unsafeCache?, useSyncFileSystemCalls? }
    at webpack (D:\code\demo\myapp\node_modules\roadhog\node_modules\webpack\lib\webpack.js:19:9)
    at realBuild (D:\code\demo\myapp\node_modules\roadhog\lib\buildDll.js:211:40)
    at D:\code\demo\myapp\node_modules\roadhog\lib\buildDll.js:109:7
    at D:\code\demo\myapp\node_modules\recursive-readdir\index.js:50:14
    at FSReqWrap.oncomplete (fs.js:114:15)

```

**Comment by kingyang** [comment]
用dva-cli初始化的新项目

**Comment by sandwich99** [comment]
#302 已修复 ， 还没有合并

**Comment by sorrycc** [comment]
+ roadhog@1.0.0-beta.5
