### ISSUE TITLE
require(...) is not a function

### ISSUE THREAD

**Issue by yuanxuegui** [sorrycc/roadhog#327]
#### Environment(required) | 环境（必填）

- roadhog version（roadhog版本）0.6.0
- Nodejs and Npm version（Nodejs 和 Npm 版本）Nodejs 7.9.0 npm 5.1.0
- Operating environment (e.g. OS name) and its version（操作系统版本）: Windows10

#### What did you do? Please provide steps to re-produce your problem.（请提供复现步骤）
const svgSpriteDirs = [
  require.resolve('antd-mobile').replace(/warn\.js$/, ''), // antd-mobile 内置svg
];
export default {
  entry: 'src/index.js',
  svgSpriteLoaderDirs: svgSpriteDirs,
 ....

#### What do you expected?（预期的正常效果）
能够加载antd-mobile svg

#### What happen?（发生了何种非正常现象）
return require(filePath)(config, env); // eslint-disable-line
                            ^

TypeError: require(...) is not a function
    at applyWebpackConfig (D:\project\9k-mobile-reg\node_modules\roadhog\lib\utils\applyWebpackConfig.js:32:29)
    at readWebpackConfig (D:\project\9k-mobile-reg\node_modules\roadhog\lib\runServer.js:99:45)
    at init (D:\project\9k-mobile-reg\node_modules\roadhog\lib\runServer.js:252:3)
    at Object.<anonymous> (D:\project\9k-mobile-reg\node_modules\roadhog\lib\runServer.js:275:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\project\9k-mobile-reg\node_modules\roadhog\lib\server.js:19:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)

**Comment by yuanxuegui** [comment]
已解决

**Comment by YuriTu** [comment]
same 

看源码是
require(filePath)这里拿到了你的webpack.config.js，如果你的config里面是个对象就会报这个错，如果使用function就会报#34 的warning

对，就是只要有个文件存在就会有这个问题，哪怕你没有使用，：（  

可是webpack config 对象的情况多一些，希望开发者在此处能加上错误提示。
