### ISSUE TITLE
新建了一个测试文件 ./test/users-test.js 

### ISSUE THREAD

**Issue by shenggen1987** [sorrycc/roadhog#43]
新建了一个测试文件
./test/users-test.js 
代码如下 

```
import expect from 'expect';
import users from '../src/models/users';

describe('reducers', () => {

  describe('reducer', () => {
    it('it should save', () => {
      expect(users.reducers['save']({}, { payload: { data:[],total:1,page:1 }})).toEqual({list:[],total:1,page:1});
    });
  })
});
```

出现如下错误， 请问babel-polyfill 要如何配置
$ roadhog test
/private/tmp/dva-example-user-dashboard/src/utils/request.js:34
  var _ref = _asyncToGenerator(regeneratorRuntime.mark(function _callee(url, options) {

**Comment by sorrycc** [comment]
难以阅读，请参考以下文档调整下格式：

- https://segmentfault.com/markdown
- https://guides.github.com/features/mastering-markdown/

**Comment by sorrycc** [comment]
错误信息没贴全?

**Comment by shenggen1987** [comment]
```
/private/tmp/dva-example-user-dashboard/src/utils/request.js:34
  var _ref = _asyncToGenerator(regeneratorRuntime.mark(function _callee(url, options) {
                               ^

ReferenceError: regeneratorRuntime is not defined
    at /private/tmp/dva-example-user-dashboard/src/utils/request.js:34:32
    at Object.<anonymous> (/private/tmp/dva-example-user-dashboard/src/utils/request.js:79:2)
    at Module._compile (module.js:556:32)
    at loader (/usr/local/lib/node_modules/roadhog/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/local/lib/node_modules/roadhog/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/private/tmp/dva-example-user-dashboard/src/services/users.js:1:1)
    at Module._compile (module.js:556:32)
    at loader (/usr/local/lib/node_modules/roadhog/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/local/lib/node_modules/roadhog/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/private/tmp/dva-example-user-dashboard/src/models/users.js:1:1)
    at Module._compile (module.js:556:32)
    at loader (/usr/local/lib/node_modules/roadhog/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/local/lib/node_modules/roadhog/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/private/tmp/dva-example-user-dashboard/test/users-test.js:2:1)
    at Module._compile (module.js:556:32)
    at loader (/usr/local/lib/node_modules/roadhog/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/local/lib/node_modules/roadhog/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at /usr/local/lib/node_modules/roadhog/node_modules/mocha/lib/mocha.js:222:27
    at Array.forEach (native)
    at Mocha.loadFiles (/usr/local/lib/node_modules/roadhog/node_modules/mocha/lib/mocha.js:219:14)
    at Mocha.run (/usr/local/lib/node_modules/roadhog/node_modules/mocha/lib/mocha.js:487:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/roadhog/node_modules/mocha/bin/_mocha:459:18)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

**Comment by sorrycc** [comment]
Bumped roadhog@0.4.3，已修复。
