### ISSUE TITLE
css 没有压缩，也没有提取设置

### ISSUE THREAD

**Issue by zkeyword** [sorrycc/roadhog#440]
#### Environment(required) | 环境（必填）

- roadhog 1.2.2
- Nodejs 8.4 and Npm 5.4.1
- win 10

#### What did you do? Please provide steps to re-produce your problem.（请提供复现步骤）

npm run build

#### What do you expected?（预期的正常效果）

- index.css 压缩
- css 文件没有提取

#### What happen?（发生了何种非正常现象）

- index.css 没有压缩
- css内联在js内

<!--
Compile or tool configuration issues: Put the sample code on GitHub/Coding.net, so we can figure it out.（构建工具或环境配置类问题请提供 github 项目示例源码偏于排查）

`{
  "entry": "src/index.js",
  "disableCSSModules": false,
  "publicPath": "/",
  "hash": true,
  "disable": false,
  "allChunks": true,
  "env": {
    "development": {
      "extraBabelPlugins": [
        "dva-hmr",
        "transform-runtime",
        ["import", { "libraryName": "antd", "libraryDirectory": "lib", "style": "css" }]
      ]
    },
    "production": {
      "extraBabelPlugins": [
        "transform-runtime",
        ["import", { "libraryName": "antd", "libraryDirectory": "lib", "style": "css" }]
      ]
    }
  }
}`

**Comment by zkeyword** [comment]
`{
  "entry": "src/index.js",
  "disableCSSModules": false,
  "publicPath": "/",
  "hash": true,
  "disable": false,
  "allChunks": true,
  "env": {
    "development": {
      "extraBabelPlugins": [
        "dva-hmr",
        "transform-runtime",
        ["import", { "libraryName": "antd", "libraryDirectory": "lib", "style": "css" }]
      ]
    },
    "production": {
      "extraBabelPlugins": [
        "transform-runtime",
        ["import", { "libraryName": "antd", "libraryDirectory": "lib", "style": "css" }]
      ]
    }
  }
}`

**Comment by zkeyword** [comment]
```
{
  "entry": "src/index.js",
  "disableCSSModules": false,
  "publicPath": "/",
  "hash": true,
  "disable": false,
  "allChunks": true,
  "env": {
    "development": {
      "extraBabelPlugins": [
        "dva-hmr",
        "transform-runtime",
        ["import", { "libraryName": "antd", "libraryDirectory": "lib", "style": "css" }]
      ]
    },
    "production": {
      "extraBabelPlugins": [
        "transform-runtime",
        ["import", { "libraryName": "antd", "libraryDirectory": "lib", "style": "css" }]
      ]
    }
  }
}
```

**Comment by zkeyword** [comment]
```
const webpack = require('webpack')
const ExtractTextPlugin = require('extract-text-webpack-plugin')

module.exports = (webpackConfig, env) => {
    const production = env === 'production'
    webpackConfig.module.rules.unshift({
        test: /\.styl$/,
        use: ['style', 'css', 'stylus']
    })
    webpackConfig.module.rules.map((item) => {
        if (item.exclude && item.exclude[2]) {
            item.exclude[2] = /\.(css|less|scss|styl)$/
        }
        return item
    })

    if (production) {
        webpackConfig.plugins.push(
            new webpack.LoaderOptionsPlugin({
                minimize: true,
                debug: false
            })
        )
        webpackConfig.plugins.push(
            new ExtractTextPlugin({
                filename: '[name].[contenthash:8].css'
            })
        )
    }
    return webpackConfig
}
```
解析stylus正常，但是想单独ExtractTextPlugin提取css，rules的规则不知道怎么改，设置LoaderOptionsPlugin之后可以压缩index.css

**Comment by zkeyword** [comment]
另外运行:
`roadhog buildDll`

报错：

```
    webpackConfig.module.rules.unshift({
                        ^

TypeError: Cannot read property 'rules' of undefined
    at module.exports (I:/test/dvaNew/webpack.config.js:6:5)
    at applyWebpackConfig (C:\Users\DYNAMX\AppData\Roaming\npm\node_modules\roadhog\lib\utils\applyWebpackConfig.js:32:29)
    at build (C:\Users\DYNAMX\AppData\Roaming\npm\node_modules\roadhog\lib\buildDll.js:85:45)
    at Object.<anonymous> (C:\Users\DYNAMX\AppData\Roaming\npm\node_modules\roadhog\lib\buildDll.js:218:3)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Function.Module.runMain (module.js:609:10)
```

**Comment by zkeyword** [comment]
```
const webpack = require('webpack')
const ExtractTextPlugin = require('extract-text-webpack-plugin')

module.exports = (webpackConfig, env) => {
    const production = env === 'production'

    if (webpackConfig.module) {
        let stylusLoader = ['style', 'css', 'stylus']

        if (production) {
            webpackConfig.plugins.push(
                new ExtractTextPlugin({
                    filename: '[name].[contenthash:8].css',
                    allChunks: true
                })
            )
            webpackConfig.plugins.push(
                new webpack.LoaderOptionsPlugin({
                    minimize: true,
                    debug: false
                })
            )
            stylusLoader = ExtractTextPlugin.extract({
                use: ['css-loader', 'stylus-loader'],
                fallback: 'style-loader'
            })
        }

        webpackConfig.module.rules.unshift({
            test: /\.styl$/,
            use: stylusLoader
        })

        webpackConfig.module.rules.map((item) => {
            if (item.exclude && item.exclude[2]) {
                item.exclude[2] = /\.(css|less|scss|styl)$/
            }
            return item
        })
    }
    return webpackConfig
}
```

已解决，希望roadhog可以直接配置stylus
