### ISSUE TITLE
updated roadhog v2.0.0.  The command roadhog -v error

### ISSUE THREAD

**Issue by elvin-gogo** [sorrycc/roadhog#538]
### updated roadhog v2.0.0.  The command roadhog -v error
``` use shell
➜  projects which node
/Users/xx/.nvm/versions/node/v7.7.3/bin/node
➜  projects roadhog -v
/Users/xx/.nvm/versions/node/v7.7.3/lib/node_modules/roadhog/bin/roadhog.js:45
    );
    ^
SyntaxError: Unexpected token )
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:425:7)
    at startup (bootstrap_node.js:146:9)
```
this is roadhog.js:
``` use js
#!/usr/bin/env node

const chalk = require('chalk');
const fork = require('child_process').fork;
require('graceful-process')();

const script = process.argv[2];
const args = process.argv.slice(3);

const nodeVersion = process.versions.node;
const versions = nodeVersion.split('.');
const major = versions[0];
const minor = versions[1];

if (major * 10 + minor * 1 < 65) {
  console.log(`Node version must >= 6.5, but got ${major}.${minor}`);
  process.exit(1);
}

var result; // eslint-disable-line

const scriptAlias = {
  server: 'dev',
};
const aliasedScript = scriptAlias[script] || script;
switch (aliasedScript) {
  case '-v':
  case '--version':
    const pkg = require('../package.json');
    console.log(pkg.version);
    if (!(pkg._from && pkg._resolved)) {
      console.log(chalk.cyan('@local'));
    }
    break;
  case 'build':
  case 'dev':
  case 'test':
    require('atool-monitor').emit();
    const proc = fork(
      require.resolve(`../lib/scripts/${aliasedScript}`),
      args,
      {
        stdio: 'inherit',
      },
    );
    proc.once('exit', code => {
      process.exit(code);
    });
    process.once('exit', () => {
      proc.kill();
    });
    break;
  default:
    console.log(`Unknown script ${chalk.cyan(script)}.`);
    break;
}

```

when I user node version stable v9.3.0, the command is ok.
``` use shell
/Users/xx/.nvm/versions/node/v9.3.0/bin/node
➜  projects roadhog -v
2.0.0
[graceful-process#15463] exit with code:0
➜  projects
```

**Comment by sorrycc** [comment]
Thanks for report, it's fixed in 2.0.1 .
