### ISSUE TITLE
TypeError: Cannot convert undefined or null to object 

### ISSUE THREAD

**Issue by joriewong** [sorrycc/roadhog#566]
roadhog版本 "^2.0.0-0"

> roadhog dev

'git' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
'git' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
'git' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
TypeError: Cannot convert undefined or null to object
    at keys (<anonymous>)
    at realApplyMock (D:\projects\cisdi\dva-curd\node_modules\_roadhog@2.0.0-rc.2@roadhog\lib\utils\mock.js:118:21)
    at applyMock (D:\projects\cisdi\dva-curd\node_modules\_roadhog@2.0.0-rc.2@roadhog\lib\utils\mock.js:87:5)
    at beforeServer (D:\projects\cisdi\dva-curd\node_modules\_roadhog@2.0.0-rc.2@roadhog\lib\dev.js:78:29)
    at then.port (D:\projects\cisdi\dva-curd\node_modules\_af-webpack@0.13.6@af-webpack\lib\dev.js:109:7)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

Failed to parse mock config.

Error in Cannot convert undefined or null to object
TypeError: Cannot convert undefined or null to object

**Comment by sorrycc** [comment]
更新到 roadhog@2 最新版，我记得已经修复的。

**Comment by joriewong** [comment]
升级至"roadhog": "^2.1.0"已解决
