### ISSUE TITLE
改进 mock 配置出错的提醒

### ISSUE THREAD

**Issue by sorrycc** [sorrycc/roadhog#59]
现在是把所有的堆栈信息全部打印了出来。

```
/Users/chencheng/Documents/Work/Misc/dva-example-user-dashboard/.roadhogrc.server.js: Unexpected token, expected { (5:21)
SyntaxError: /Users/chencheng/Documents/Work/Misc/dva-example-user-dashboard/.roadhogrc.server.js: Unexpected token, expected { (5:21)
  3 |   '/xxx/a': (req, res) => res.end('asd'),
  4 |   '/xxx/b': (req, res) => res.end('xxx/bbd'),
> 5 |   '/xxx/c'(req, res) => res.end('xxx/e'),
    |                      ^
  6 |   '/xxx/f': (req, res) => res.end('xxx/f'),
  7 |   '/xxx/g': (req, res) => res.end('xxx/a'),
  8 |   '/xxx/h': (req, res) => res.end('ahh'),
    at Parser.pp$5.raise (/Users/chencheng/Documents/Work/Misc/roadhog/node_modules/.6.14.1@babylon/lib/index.js:4246:13)
    at Parser.pp.unexpected (/Users/chencheng/Documents/Work/Misc/roadhog/node_modules/.6.14.1@babylon/lib/index.js:1627:8)
    at Parser.pp.expect (/Users/chencheng/Documents/Work/Misc/roadhog/node_modules/.6.14.1@babylon/lib/index.js:1615:33)
    at Parser.pp$1.parseBlock (/Users/chencheng/Documents/Work/Misc/roadhog/node_modules/.6.14.1@babylon/lib/index.js:2113:8)
    at Parser.pp$3.parseFunctionBody (/Users/chencheng/Documents/Work/Misc/roadhog/node_modules/.6.14.1@babylon/lib/index.js:3998:22)
    at Parser.parseFunctionBody (/Users/chencheng/Documents/Work/Misc/roadhog/node_modules/.6.14.1@babylon/lib/index.js:5205:20)
    at Parser.pp$3.parseMethod (/Users/chencheng/Documents/Work/Misc/roadhog/node_modules/.6.14.1@babylon/lib/index.js:3967:8)
    at Parser.pp$3.parseObjPropValue (/Users/chencheng/Documents/Work/Misc/roadhog/node_modules/.6.14.1@babylon/lib/index.js:3891:10)
    at Parser.parseObjPropValue (/Users/chencheng/Documents/Work/Misc/roadhog/node_modules/.6.14.1@babylon/lib/index.js:5531:13)
    at Parser.pp$3.parseObj (/Users/chencheng/Documents/Work/Misc/roadhog/node_modules/.6.14.1@babylon/lib/index.js:3865:10)
    at Parser.pp$3.parseExprAtom (/Users/chencheng/Documents/Work/Misc/roadhog/node_modules/.6.14.1@babylon/lib/index.js:3555:19)
    at Parser.parseExprAtom (/Users/chencheng/Documents/Work/Misc/roadhog/node_modules/.6.14.1@babylon/lib/index.js:6402:22)
    at Parser.pp$3.parseExprSubscripts (/Users/chencheng/Documents/Work/Misc/roadhog/node_modules/.6.14.1@babylon/lib/index.js:3331:19)
    at Parser.pp$3.parseMaybeUnary (/Users/chencheng/Documents/Work/Misc/roadhog/node_modules/.6.14.1@babylon/lib/index.js:3311:19)
    at Parser.pp$3.parseExprOps (/Users/chencheng/Documents/Work/Misc/roadhog/node_modules/.6.14.1@babylon/lib/index.js:3241:19)
    at Parser.pp$3.parseMaybeConditional (/Users/chencheng/Documents/Work/Misc/roadhog/node_modules/.6.14.1@babylon/lib/index.js:3218:19)
```

**Comment by sorrycc** [comment]
期望输出：

```
Error in ./.roadhogrc.server.js
Syntax error: Unexpected token, expected { (5:21)

  3 |   '/xxx/a': (req, res) => res.end('asd'),
  4 |   '/xxx/b': (req, res) => res.end('xxx/bbd'),
> 5 |   '/xxx/c'(req, res) => res.end('xxx/e'),
    |                      ^
  6 |   '/xxx/f': (req, res) => res.end('xxx/f'),
  7 |   '/xxx/g': (req, res) => res.end('xxx/a'),
  8 |   '/xxx/h': (req, res) => res.end('ahh'),
```

**Comment by sorrycc** [comment]
![](https://zos.alipayobjects.com/rmsportal/GIcgzsstGKlQTqgkXCVC.png)
