### ISSUE TITLE
Failed to minify the bundle. Error: index.js from UglifyJs

### ISSUE THREAD

**Issue by heiyanshooter** [sorrycc/roadhog#622]
#### Environment(required) | 环境（必填）

- roadhog 2.2.0（roadhog版本）
- nodejs^v8.1.1 npm^5.0.3
- windows 7:

#### What did you do? Please provide steps to re-produce your problem.（请提供复现步骤）

![image](https://user-images.githubusercontent.com/22254129/36525347-882a8262-17e4-11e8-8981-4f1fb5ccc13e.png)

#### What do you expected?（预期的正常效果）

压缩成功

#### What happen?（发生了何种非正常现象）

无法压缩成功，加了babel/preset-env后也是完全同样的结果

**Comment by sorrycc** [comment]
依赖里有用了非 es5 语法。

**Comment by heiyanshooter** [comment]
但是我加了babel/preset-env后也是完全同样的结果，我是这样的写法有问题吗
![image](https://user-images.githubusercontent.com/22254129/36525861-c1401628-17e6-11e8-8736-18e8c23943d9.png)

**Comment by heiyanshooter** [comment]
我把问题解决了，webpack用babel转换代码时不会转换依赖的代码，不知道是不是这样理解的，谢谢大佬

**Comment by sorrycc** [comment]
是的。

**Comment by echoescn** [comment]
@heiyanshooter 怎么解决的

**Comment by JakimLi** [comment]
@heiyanshooter 怎么解决的

**Comment by rookie1989** [comment]
@heiyanshooter  求解决方案

**Comment by heiyanshooter** [comment]
解决方法看这篇文件 https://zhuanlan.zhihu.com/p/35645287，文章作者就这个项目的作者

**Comment by echoescn** [comment]
@heiyanshooter 我也是找到这里解决了这个问题

**Comment by gebilaoman** [comment]
更了一系列的package.json插件就好了

**Comment by pengshaosu** [comment]
> 我把问题解决了，webpack用babel转换代码时不会转换依赖的代码，不知道是不是这样理解的，谢谢大佬

就是说webpack构建时，babel只转换项目文件，不对npm包转换，

**Comment by pengshaosu** [comment]
uglify 压缩报错问题及 es5-imcompatible-versions #68

**Comment by pengshaosu** [comment]
参见： https://github.com/sorrycc/blog/issues/68

**Comment by zjjjjjjjjjjd** [comment]
@heiyanshooter 请问我该怎么做呢？看了文章只看懂了在必要的时候在extraBabelIncludes添加一些不支持的包，但是我要怎么从报错信息中看出来是哪个包出错了呢？（es5ImcompatibleVersions已经加过）
`Failed to minify the bundle. Error: index.js from UglifyJs
Unexpected token: name (root) [index.js:72442,4]
    at doneHandler (D:\git\test\nw\template-dva\node_modules\af-webpack\lib\build.js:91:27)
    at emitRecords.err (D:\git\test\nw\template-dva\node_modules\webpack\lib\Compiler.js:265:13)
    at Compiler.emitRecords (D:\git\test\nw\template-dva\node_modules\webpack\lib\Compiler.js:371:38)
    at emitAssets.err (D:\git\test\nw\template-dva\node_modules\webpack\lib\Compiler.js:258:10)
    at applyPluginsAsyncSeries1.err (D:\git\test\nw\template-dva\node_modules\webpack\lib\Compiler.js:364:12)
    at next (D:\git\test\nw\template-dva\node_modules\tapable\lib\Tapable.js:218:11)
    at Compiler.compiler.plugin (D:\git\test\nw\template-dva\node_modules\webpack\lib\performance\SizeLimitsPlugin.js:99:4)
    at next (D:\git\test\nw\template-dva\node_modules\tapable\lib\Tapable.js:220:14)
    at callback (D:\git\test\nw\template-dva\node_modules\copy-webpack-plugin\dist\index.js:126:17)
    at Compiler.afterEmit (D:\git\test\nw\template-dva\node_modules\copy-webpack-plugin\dist\index.js:220:13)
    at Compiler.applyPluginsAsyncSeries1 (D:\git\test\nw\template-dva\node_modules\tapable\lib\Tapable.js:222:13)
    at Compiler.afterEmit (D:\git\test\nw\template-dva\node_modules\webpack\lib\Compiler.js:361:9)
    at require.forEach.err (D:\git\test\nw\template-dva\node_modules\webpack\lib\Compiler.js:350:15)
    at D:\git\test\nw\template-dva\node_modules\async\dist\async.js:473:16
    at iteratorCallback (D:\git\test\nw\template-dva\node_modules\async\dist\async.js:1064:13)
    at D:\git\test\nw\template-dva\node_modules\async\dist\async.js:969:16
Read more here: http://bit.ly/2tRViJ9

[graceful-process#12080] exit with code:1`

**Comment by SilentFlute** [comment]
@zjjjjjjjjjjd 这一行：
Unexpected token: name (root) [index.js:72442,4]
找到index.js文件，打开，然后定位到这个文件的第72442行，就是这个位置报错了

**Comment by ganyanchuan1989** [comment]
详见：https://github.com/sorrycc/blog/issues/68
