### ISSUE TITLE
npm start 报错 Cannot read property 'compilation' of undefined

### ISSUE THREAD

**Issue by kqdjacky** [sorrycc/roadhog#843]
roadhog : ^2.5.0-beta.2
node: v10.14.2
npm: 6.5.0

```
Failed to compile.

TypeError: Cannot read property 'compilation' of undefined
    at ProgressPlugin.apply (survey-management/node_modules/webpack/lib/ProgressPlugin.js:193:19)
    at Compiler.apply (survey-management/node_modules/roadhog/node_modules/webpack/node_modules/tapable/lib/Tapable.js:375:16)
    at webpack (/survey-management/node_modules/roadhog/node_modules/webpack/lib/webpack.js:33:19)
    at createCompiler (survey-management/node_modules/roadhog/node_modules/af-webpack/lib/WebpackDevServerUtils.js:108:16)
    at then.port (survey-management/node_modules/roadhog/node_modules/af-webpack/lib/dev.js:65:64)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by TP026787** [comment]
同样的问题，希望有解决的方法

**Comment by sorrycc** [comment]
加环境变量 `PROGRESS=none` 试试。

**Comment by wsf1214** [comment]
项目中的babel升级到了7.0，"roadhog": "^2.5.0-beta.4", 然后run start的时候就会这个错，加环境变量 PROGRESS=none也没有用，希望尽快解决

**Comment by wsf1214** [comment]
> 加环境变量 `PROGRESS=none` 试试。

项目中的babel升级到了7.0，"roadhog": "^2.5.0-beta.4", 然后run start的时候就会这个错，加环境变量 PROGRESS=none也没有用，希望尽快解决

**Comment by xuanxuan321** [comment]
maybe you are using webpack@3.X version,but  webpack@4.X is required. you need downgrade to uglifyjs-webpack-plugin@1.X, or update your configuration to webpack@4.X. remember webpack@3 requires uglifyjs-webpack-plugin@1, webpack@4 requires uglifyjs-webpack-plugin@2

**Comment by wsf1214** [comment]
@xuanxuan321  but I do not use  uglifyjs-webpack-plugin

**Comment by ikorason** [comment]
i have the same problem, roadhog uses webpack@3.x but when i install webpack in devDependencies as webpack@4.x it will show this error, i used npm ls webpack to check, it shows that roadhog uses af-webpack and af-webpack is locked to webpack 3, af-webpack needs update for roadhog

**Comment by itdotaer** [comment]
这个问题还没解决吗

**Comment by chenc041** [comment]
解决方案:
在当前目录下重新安装下webpack 就好了

**Comment by jintangWang** [comment]
都2019年了还没修复么。。。
先把根目录下的 `webpack` 回退到 3版本 来启动项目好了
``` bash
npm install webpack@3.12.0
```

**Comment by TP026787** [comment]
解决了，可能是package依赖的问题，npm在安装依赖的时候选择的版本有问题，在package添加"roadhog": "^2.5.0-beta.4"后选择使用yarn install就可以运行了，如果使用npm就不能解决问题，但是我npm确认已经升级过了，所以觉得应该是npm选择依赖时版本有问题。。。

**Comment by Boxser567** [comment]
`npm build` when you throw the Error in Vue@2.x , check your `package.json` if exist `"optimize-css-assets-webpack-plugin": "5.0.1"`，
`npm i optimize-css-assets-webpack-plugin@3.2.0` 
 remove node_modules and npm install again gone be fine(我写给老外看么...)

**Comment by vipcxj** [comment]
放弃roadhog，直接用webpack4，实际上webpack做了零参数升级，所以自己配置也没那么难~ 这样对ide也比较友好，因为不少ide会自动识别webpack的配置文件，但肯定认不出roadhog的~
